import turtle

# Block blue
blue0 = turtle.Turtle()
blue0.speed(0)
blue0.shape("square")
blue0.color("blue")
blue0.shapesize(stretch_wid=1, stretch_len=5)
blue0.penup()
blue0.goto(0, 50)

blue1 = turtle.Turtle()
blue1.speed(0)
blue1.shape("square")
blue1.color("blue")
blue1.shapesize(stretch_wid=1, stretch_len=5)
blue1.penup()
blue1.goto(110, 50)

blueM1 = turtle.Turtle()
blueM1.speed(0)
blueM1.shape("square")
blueM1.color("blue")
blueM1.shapesize(stretch_wid=1, stretch_len=5)
blueM1.penup()
blueM1.goto(-110, 50)

blue2 = turtle.Turtle()
blue2.speed(0)
blue2.shape("square")
blue2.color("blue")
blue2.shapesize(stretch_wid=1, stretch_len=5)
blue2.penup()
blue2.goto(220, 50)

blueM2 = turtle.Turtle()
blueM2.speed(0)
blueM2.shape("square")
blueM2.color("blue")
blueM2.shapesize(stretch_wid=1, stretch_len=5)
blueM2.penup()
blueM2.goto(-220, 50)

blue3 = turtle.Turtle()
blue3.speed(0)
blue3.shape("square")
blue3.color("blue")
blue3.shapesize(stretch_wid=1, stretch_len=5)
blue3.penup()
blue3.goto(330, 50)

blueM3 = turtle.Turtle()
blueM3.speed(0)
blueM3.shape("square")
blueM3.color("blue")
blueM3.shapesize(stretch_wid=1, stretch_len=5)
blueM3.penup()
blueM3.goto(-330, 50)

blue4 = turtle.Turtle()
blue4.speed(0)
blue4.shape("square")
blue4.color("blue")
blue4.shapesize(stretch_wid=1, stretch_len=5)
blue4.penup()
blue4.goto(440, 50)

blueM4 = turtle.Turtle()
blueM4.speed(0)
blueM4.shape("square")
blueM4.color("blue")
blueM4.shapesize(stretch_wid=1, stretch_len=5)
blueM4.penup()
blueM4.goto(-440, 50)

# Block greens
green0 = turtle.Turtle()
green0.speed(0)
green0.shape("square")
green0.color("green")
green0.shapesize(stretch_wid=1, stretch_len=5)
green0.penup()
green0.goto(0, 80)

green1 = turtle.Turtle()
green1.speed(0)
green1.shape("square")
green1.color("green")
green1.shapesize(stretch_wid=1, stretch_len=5)
green1.penup()
green1.goto(110, 80)

greenM1 = turtle.Turtle()
greenM1.speed(0)
greenM1.shape("square")
greenM1.color("green")
greenM1.shapesize(stretch_wid=1, stretch_len=5)
greenM1.penup()
greenM1.goto(-110, 80)

green2 = turtle.Turtle()
green2.speed(0)
green2.shape("square")
green2.color("green")
green2.shapesize(stretch_wid=1, stretch_len=5)
green2.penup()
green2.goto(220, 80)

greenM2 = turtle.Turtle()
greenM2.speed(0)
greenM2.shape("square")
greenM2.color("green")
greenM2.shapesize(stretch_wid=1, stretch_len=5)
greenM2.penup()
greenM2.goto(-220, 80)

green3 = turtle.Turtle()
green3.speed(0)
green3.shape("square")
green3.color("green")
green3.shapesize(stretch_wid=1, stretch_len=5)
green3.penup()
green3.goto(330, 80)

greenM3 = turtle.Turtle()
greenM3.speed(0)
greenM3.shape("square")
greenM3.color("green")
greenM3.shapesize(stretch_wid=1, stretch_len=5)
greenM3.penup()
greenM3.goto(-330, 80)

green4 = turtle.Turtle()
green4.speed(0)
green4.shape("square")
green4.color("green")
green4.shapesize(stretch_wid=1, stretch_len=5)
green4.penup()
green4.goto(440, 80)

greenM4 = turtle.Turtle()
greenM4.speed(0)
greenM4.shape("square")
greenM4.color("green")
greenM4.shapesize(stretch_wid=1, stretch_len=5)
greenM4.penup()
greenM4.goto(-440, 80)

# Block greens
yellow0 = turtle.Turtle()
yellow0.speed(0)
yellow0.shape("square")
yellow0.color("yellow")
yellow0.shapesize(stretch_wid=1, stretch_len=5)
yellow0.penup()
yellow0.goto(0, 110)

# green1 = turtle.Turtle()
# green1.speed(0)
# green1.shape("square")
# green1.color("green")
# green1.shapesize(stretch_wid=1, stretch_len=5)
# green1.penup()
# green1.goto(110, 80)

# greenM1 = turtle.Turtle()
# greenM1.speed(0)
# greenM1.shape("square")
# greenM1.color("green")
# greenM1.shapesize(stretch_wid=1, stretch_len=5)
# greenM1.penup()
# greenM1.goto(-110, 80)

# green2 = turtle.Turtle()
# green2.speed(0)
# green2.shape("square")
# green2.color("green")
# green2.shapesize(stretch_wid=1, stretch_len=5)
# green2.penup()
# green2.goto(220, 80)

# greenM2 = turtle.Turtle()
# greenM2.speed(0)
# greenM2.shape("square")
# greenM2.color("green")
# greenM2.shapesize(stretch_wid=1, stretch_len=5)
# greenM2.penup()
# greenM2.goto(-220, 80)

# green3 = turtle.Turtle()
# green3.speed(0)
# green3.shape("square")
# green3.color("green")
# green3.shapesize(stretch_wid=1, stretch_len=5)
# green3.penup()
# green3.goto(330, 80)

# greenM3 = turtle.Turtle()
# greenM3.speed(0)
# greenM3.shape("square")
# greenM3.color("green")
# greenM3.shapesize(stretch_wid=1, stretch_len=5)
# greenM3.penup()
# greenM3.goto(-330, 80)

# green4 = turtle.Turtle()
# green4.speed(0)
# green4.shape("square")
# green4.color("green")
# green4.shapesize(stretch_wid=1, stretch_len=5)
# green4.penup()
# green4.goto(440, 80)

# greenM4 = turtle.Turtle()
# greenM4.speed(0)
# greenM4.shape("square")
# greenM4.color("green")
# greenM4.shapesize(stretch_wid=1, stretch_len=5)
# greenM4.penup()
# greenM4.goto(-440, 80)