import turtle

# Block blue
blue0 = turtle.Turtle()
blue0.speed(0)
blue0.shape("square")
blue0.color("blue")
blue0.shapesize(stretch_wid=1, stretch_len=5)
blue0.penup()
blue0.goto(0, 50)

blue1 = turtle.Turtle()
blue1.speed(0)
blue1.shape("square")
blue1.color("blue")
blue1.shapesize(stretch_wid=1, stretch_len=5)
blue1.penup()
blue1.goto(110, 50)

blueM1 = turtle.Turtle()
blueM1.speed(0)
blueM1.shape("square")
blueM1.color("blue")
blueM1.shapesize(stretch_wid=1, stretch_len=5)
blueM1.penup()
blueM1.goto(-110, 50)

blue2 = turtle.Turtle()
blue2.speed(0)
blue2.shape("square")
blue2.color("blue")
blue2.shapesize(stretch_wid=1, stretch_len=5)
blue2.penup()
blue2.goto(220, 50)

blueM2 = turtle.Turtle()
blueM2.speed(0)
blueM2.shape("square")
blueM2.color("blue")
blueM2.shapesize(stretch_wid=1, stretch_len=5)
blueM2.penup()
blueM2.goto(-220, 50)

blue3 = turtle.Turtle()
blue3.speed(0)
blue3.shape("square")
blue3.color("blue")
blue3.shapesize(stretch_wid=1, stretch_len=5)
blue3.penup()
blue3.goto(330, 50)

blueM3 = turtle.Turtle()
blueM3.speed(0)
blueM3.shape("square")
blueM3.color("blue")
blueM3.shapesize(stretch_wid=1, stretch_len=5)
blueM3.penup()
blueM3.goto(-330, 50)

blue4 = turtle.Turtle()
blue4.speed(0)
blue4.shape("square")
blue4.color("blue")
blue4.shapesize(stretch_wid=1, stretch_len=5)
blue4.penup()
blue4.goto(440, 50)

blueM4 = turtle.Turtle()
blueM4.speed(0)
blueM4.shape("square")
blueM4.color("blue")
blueM4.shapesize(stretch_wid=1, stretch_len=5)
blueM4.penup()
blueM4.goto(-440, 50)

# Block greens
green0 = turtle.Turtle()
green0.speed(0)
green0.shape("square")
green0.color("green")
green0.shapesize(stretch_wid=1, stretch_len=5)
green0.penup()
green0.goto(0, 80)

green1 = turtle.Turtle()
green1.speed(0)
green1.shape("square")
green1.color("green")
green1.shapesize(stretch_wid=1, stretch_len=5)
green1.penup()
green1.goto(110, 80)

greenM1 = turtle.Turtle()
greenM1.speed(0)
greenM1.shape("square")
greenM1.color("green")
greenM1.shapesize(stretch_wid=1, stretch_len=5)
greenM1.penup()
greenM1.goto(-110, 80)

green2 = turtle.Turtle()
green2.speed(0)
green2.shape("square")
green2.color("green")
green2.shapesize(stretch_wid=1, stretch_len=5)
green2.penup()
green2.goto(220, 80)

greenM2 = turtle.Turtle()
greenM2.speed(0)
greenM2.shape("square")
greenM2.color("green")
greenM2.shapesize(stretch_wid=1, stretch_len=5)
greenM2.penup()
greenM2.goto(-220, 80)

green3 = turtle.Turtle()
green3.speed(0)
green3.shape("square")
green3.color("green")
green3.shapesize(stretch_wid=1, stretch_len=5)
green3.penup()
green3.goto(330, 80)

greenM3 = turtle.Turtle()
greenM3.speed(0)
greenM3.shape("square")
greenM3.color("green")
greenM3.shapesize(stretch_wid=1, stretch_len=5)
greenM3.penup()
greenM3.goto(-330, 80)

green4 = turtle.Turtle()
green4.speed(0)
green4.shape("square")
green4.color("green")
green4.shapesize(stretch_wid=1, stretch_len=5)
green4.penup()
green4.goto(440, 80)

greenM4 = turtle.Turtle()
greenM4.speed(0)
greenM4.shape("square")
greenM4.color("green")
greenM4.shapesize(stretch_wid=1, stretch_len=5)
greenM4.penup()
greenM4.goto(-440, 80)

# Block yellow
yellow0 = turtle.Turtle()
yellow0.speed(0)
yellow0.shape("square")
yellow0.color("yellow")
yellow0.shapesize(stretch_wid=1, stretch_len=5)
yellow0.penup()
yellow0.goto(0, 110)

yellow1 = turtle.Turtle()
yellow1.speed(0)
yellow1.shape("square")
yellow1.color("yellow")
yellow1.shapesize(stretch_wid=1, stretch_len=5)
yellow1.penup()
yellow1.goto(110, 110)

yellowM1 = turtle.Turtle()
yellowM1.speed(0)
yellowM1.shape("square")
yellowM1.color("yellow")
yellowM1.shapesize(stretch_wid=1, stretch_len=5)
yellowM1.penup()
yellowM1.goto(-110, 110)

yellow2 = turtle.Turtle()
yellow2.speed(0)
yellow2.shape("square")
yellow2.color("yellow")
yellow2.shapesize(stretch_wid=1, stretch_len=5)
yellow2.penup()
yellow2.goto(220, 110)

yellowM2 = turtle.Turtle()
yellowM2.speed(0)
yellowM2.shape("square")
yellowM2.color("yellow")
yellowM2.shapesize(stretch_wid=1, stretch_len=5)
yellowM2.penup()
yellowM2.goto(-220, 110)

yellow3 = turtle.Turtle()
yellow3.speed(0)
yellow3.shape("square")
yellow3.color("yellow")
yellow3.shapesize(stretch_wid=1, stretch_len=5)
yellow3.penup()
yellow3.goto(330, 110)

yellowM3 = turtle.Turtle()
yellowM3.speed(0)
yellowM3.shape("square")
yellowM3.color("yellow")
yellowM3.shapesize(stretch_wid=1, stretch_len=5)
yellowM3.penup()
yellowM3.goto(-330, 110)

yellow4 = turtle.Turtle()
yellow4.speed(0)
yellow4.shape("square")
yellow4.color("yellow")
yellow4.shapesize(stretch_wid=1, stretch_len=5)
yellow4.penup()
yellow4.goto(440, 110)

yellowM4 = turtle.Turtle()
yellowM4.speed(0)
yellowM4.shape("square")
yellowM4.color("yellow")
yellowM4.shapesize(stretch_wid=1, stretch_len=5)
yellowM4.penup()
yellowM4.goto(-440, 110)

# # Block orange
orange0 = turtle.Turtle()
orange0.speed(0)
orange0.shape("square")
orange0.color("orange")
orange0.shapesize(stretch_wid=1, stretch_len=5)
orange0.penup()
orange0.goto(0, 140)

orange1 = turtle.Turtle()
orange1.speed(0)
orange1.shape("square")
orange1.color("orange")
orange1.shapesize(stretch_wid=1, stretch_len=5)
orange1.penup()
orange1.goto(110, 140)

orangeM1 = turtle.Turtle()
orangeM1.speed(0)
orangeM1.shape("square")
orangeM1.color("orange")
orangeM1.shapesize(stretch_wid=1, stretch_len=5)
orangeM1.penup()
orangeM1.goto(-110, 140)

orange2 = turtle.Turtle()
orange2.speed(0)
orange2.shape("square")
orange2.color("orange")
orange2.shapesize(stretch_wid=1, stretch_len=5)
orange2.penup()
orange2.goto(220, 140)

orangeM2 = turtle.Turtle()
orangeM2.speed(0)
orangeM2.shape("square")
orangeM2.color("orange")
orangeM2.shapesize(stretch_wid=1, stretch_len=5)
orangeM2.penup()
orangeM2.goto(-220, 140)

orange3 = turtle.Turtle()
orange3.speed(0)
orange3.shape("square")
orange3.color("orange")
orange3.shapesize(stretch_wid=1, stretch_len=5)
orange3.penup()
orange3.goto(330, 140)

orangeM3 = turtle.Turtle()
orangeM3.speed(0)
orangeM3.shape("square")
orangeM3.color("orange")
orangeM3.shapesize(stretch_wid=1, stretch_len=5)
orangeM3.penup()
orangeM3.goto(-330, 140)

orange4 = turtle.Turtle()
orange4.speed(0)
orange4.shape("square")
orange4.color("orange")
orange4.shapesize(stretch_wid=1, stretch_len=5)
orange4.penup()
orange4.goto(440, 140)

orangeM4 = turtle.Turtle()
orangeM4.speed(0)
orangeM4.shape("square")
orangeM4.color("orange")
orangeM4.shapesize(stretch_wid=1, stretch_len=5)
orangeM4.penup()
orangeM4.goto(-440, 140)

# Block red
red0 = turtle.Turtle()
red0.speed(0)
red0.shape("square")
red0.color("red")
red0.shapesize(stretch_wid=1, stretch_len=5)
red0.penup()
red0.goto(0, 170)

red1 = turtle.Turtle()
red1.speed(0)
red1.shape("square")
red1.color("red")
red1.shapesize(stretch_wid=1, stretch_len=5)
red1.penup()
red1.goto(110, 170)

redM1 = turtle.Turtle()
redM1.speed(0)
redM1.shape("square")
redM1.color("red")
redM1.shapesize(stretch_wid=1, stretch_len=5)
redM1.penup()
redM1.goto(-110, 170)

red2 = turtle.Turtle()
red2.speed(0)
red2.shape("square")
red2.color("red")
red2.shapesize(stretch_wid=1, stretch_len=5)
red2.penup()
red2.goto(220, 170)

redM2 = turtle.Turtle()
redM2.speed(0)
redM2.shape("square")
redM2.color("red")
redM2.shapesize(stretch_wid=1, stretch_len=5)
redM2.penup()
redM2.goto(-220, 170)

red3 = turtle.Turtle()
red3.speed(0)
red3.shape("square")
red3.color("red")
red3.shapesize(stretch_wid=1, stretch_len=5)
red3.penup()
red3.goto(330, 170)

redM3 = turtle.Turtle()
redM3.speed(0)
redM3.shape("square")
redM3.color("red")
redM3.shapesize(stretch_wid=1, stretch_len=5)
redM3.penup()
redM3.goto(-330, 170)

red4 = turtle.Turtle()
red4.speed(0)
red4.shape("square")
red4.color("red")
red4.shapesize(stretch_wid=1, stretch_len=5)
red4.penup()
red4.goto(440, 170)

redM4 = turtle.Turtle()
redM4.speed(0)
redM4.shape("square")
redM4.color("red")
redM4.shapesize(stretch_wid=1, stretch_len=5)
redM4.penup()
redM4.goto(-440, 170)